### ISSUE TITLE
qq music  API文档无法访问

### ISSUE THREAD

**Issue by ashin-person** [Rain120/rain120#1]
大佬，你好！qq音乐api的文档不能访问。本人对你的qq music API这个特别感兴趣。1123842546，这个是小弟的qq，希望能和大神交流下

**Comment by Rain120** [comment]
@ashin-person 
**感谢你的关注**

1. 非常不好意思，这么晚才看到消息
2. qq 文档不能访问，应该是你GitHub访问不正常
3. 有关于qq music 的问题，可以在 [here](https://github.com/Rain120/qq-music-api)提 issue，关于这个仓库的问题，我会每1-2天会刷新，比较及时。

**Comment by ashin-person** [comment]
你好！请问有计划做登录接口吗？如果有登录接口，这个项目是如虎添翼啊







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rain120/rain120"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月20日(星期五) 晚上7:13
收件人:&nbsp;"Rain120/rain120"<rain120@noreply.github.com&gt;;
抄送:&nbsp;"/xmao 小信的星期八"<1123842546@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Rain120/rain120] qq music  API文档无法访问 (#1)





 
@ashin-person
 感谢你的关注
  
非常不好意思，这么晚才看到消息
 
qq 文档不能访问，应该是你GitHub访问不正常
 
有关于qq music 的问题，可以在 here提 issue，关于这个仓库的问题，我会每1-2天会刷新，比较及时。

**Comment by Rain120** [comment]
@ashin-person 
在项目中有个issue提过方案，但是一直都有在忙，所以一直没去调研，之后有机会应该会接入，也可能会重构，也欢迎pr，谢谢
